export const ProjectStatus = {
  NEW: 'NEW',
  PRE_BUDGET: 'PRE_BUDGET',
  CLIENT_AWAITING_CONTACT: 'CLIENT_AWAITING_CONTACT',
  AWAITING_RETRY: 'AWAITING_RETRY',
  RETRYING: 'RETRYING',
  SCHEDULED_TECHNICAL_VISIT: 'SCHEDULED_TECHNICAL_VISIT',
  TECHNICAL_VISIT_COMPLETED: 'TECHNICAL_VISIT_COMPLETED',
  FINAL_BUDGET: 'FINAL_BUDGET',
  AWAITING_MATERIALS: 'AWAITING_MATERIALS',
  SCHEDULED_INSTALLING_VISIT: 'SCHEDULED_INSTALLING_VISIT',
  INSTALLED: 'INSTALLED',
  COMPLETED: 'COMPLETED',
  NEGOTIATION_FAILED: 'NEGOTIATION_FAILED',
} as const;

export type ProjectStatusType =
  typeof ProjectStatus[keyof typeof ProjectStatus];
